name: Setup Project
description: 'Sets up the project by installing dependencies and building the project.'

inputs:
  pnpm-version:
    description: 'The version of pnpm to use for installing dependencies.'
    required: false
    default: 9.15.3
  node-version:
    description: 'The version of Node.js to use for building the project.'
    required: false
    default: '22.13.0'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
      shell: bash
    - name: Build project
      run: pnpm build
      shell: bash
